// <auto-generated />
using System;
using API_Powered_Hospital_Delivery_Robot.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Powered_Hospital_Delivery_Robot.Migrations
{
    [DbContext(typeof(RobotManagerContext))]
    [Migration("20251111133251_updateTableDesPatientTaskstop")]
    partial class updateTableDesPatientTaskstop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Alert", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("enum('battery','network','obstacle','system','manual')")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<ulong?>("PrescriptionItemId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("prescription_item_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<ulong>("RobotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('low','medium','high','critical')")
                        .HasColumnName("severity")
                        .HasDefaultValueSql("'low'");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('open','acknowledged','resolved')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'open'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PrescriptionItemId" }, "IX_alerts_prescription_item_id");

                    b.HasIndex(new[] { "RobotId" }, "fk_alert_robot");

                    b.HasIndex(new[] { "Category" }, "idx_alert_category");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_alert_created");

                    b.HasIndex(new[] { "Status" }, "idx_alert_status");

                    b.ToTable("alerts");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.CompartmentAssignment", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("CompartmentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("compartment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ItemDesc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_desc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','loaded','unlocked','delivered','locked','canceled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<ulong>("StopId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("stop_id");

                    b.Property<ulong>("TaskId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompartmentId" }, "fk_ca_comp");

                    b.HasIndex(new[] { "TaskId" }, "fk_ca_task");

                    b.HasIndex(new[] { "Status" }, "idx_ca_status");

                    b.HasIndex(new[] { "StopId", "CompartmentId" }, "uk_stop_comp")
                        .IsUnique();

                    b.ToTable("compartment_assignments");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.CompartmentCategory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("compartment_categories");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Destination", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Floor")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("floor");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<float?>("XCoordinate")
                        .HasColumnType("float")
                        .HasColumnName("x_coordinate");

                    b.Property<float?>("YCoordinate")
                        .HasColumnType("float")
                        .HasColumnName("y_coordinate");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name1");

                    b.ToTable("destinations");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.DrugCategory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique()
                        .HasDatabaseName("name2");

                    b.ToTable("drug_categories");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Log", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('success','warning','error','drive','info','broadcast','mic')")
                        .HasColumnName("log_type")
                        .HasDefaultValueSql("'info'");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<ulong>("RobotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_id");

                    b.Property<ulong?>("StopId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("stop_id");

                    b.Property<ulong?>("TaskId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StopId" }, "fk_log_stop");

                    b.HasIndex(new[] { "TaskId" }, "fk_log_task");

                    b.HasIndex(new[] { "RobotId", "CreatedAt" }, "idx_logs_robot_time");

                    b.HasIndex(new[] { "LogType" }, "idx_logs_type");

                    b.ToTable("logs");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Map", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float?>("FreeThresh")
                        .HasColumnType("float")
                        .HasColumnName("free_thresh");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("height");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("longblob")
                        .HasColumnName("image_data");

                    b.Property<string>("ImageName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_name");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("map_name");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<sbyte?>("Negate")
                        .HasColumnType("tinyint")
                        .HasColumnName("negate");

                    b.Property<float?>("OccupiedThresh")
                        .HasColumnType("float")
                        .HasColumnName("occupied_thresh");

                    b.Property<float?>("OriginX")
                        .HasColumnType("float")
                        .HasColumnName("origin_x");

                    b.Property<float?>("OriginY")
                        .HasColumnType("float")
                        .HasColumnName("origin_y");

                    b.Property<float?>("OriginZ")
                        .HasColumnType("float")
                        .HasColumnName("origin_z");

                    b.Property<float?>("Resolution")
                        .HasColumnType("float")
                        .HasColumnName("resolution");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("maps");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Medicine", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiry_date");

                    b.Property<string>("MedicineCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("medicine_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('active','expired')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'");

                    b.Property<int?>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "fk_medicine_category");

                    b.HasIndex(new[] { "MedicineCode" }, "medicine_code")
                        .IsUnique();

                    b.ToTable("medicines");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("department");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('male','female','other')")
                        .HasColumnName("gender")
                        .HasDefaultValueSql("'other'");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("patient_code");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<ulong?>("RoomId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("room_id");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("room_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('active','discharged')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoomId" }, "fk_patients_rooms");

                    b.HasIndex(new[] { "PatientCode" }, "patient_code")
                        .IsUnique();

                    b.ToTable("patients");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.PerformanceHistory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Destinations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destinations");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int")
                        .HasColumnName("error_count");

                    b.Property<ulong>("RobotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompletionDate" }, "idx_perf_date");

                    b.HasIndex(new[] { "RobotId", "CompletionDate" }, "idx_perf_robot_date");

                    b.ToTable("performance_history");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Prescription", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("PatientId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("patient_id");

                    b.Property<string>("PrescriptionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("prescription_code");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','approved','dispensed','canceled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<ulong?>("UsersId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("users_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "fk_presc_patient");

                    b.HasIndex(new[] { "UsersId" }, "fk_presc_users");

                    b.HasIndex(new[] { "PrescriptionCode" }, "prescription_code")
                        .IsUnique();

                    b.ToTable("prescriptions");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.PrescriptionItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Dosage")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("dosage");

                    b.Property<string>("Instructions")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("instructions");

                    b.Property<ulong>("MedicineId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("medicine_id");

                    b.Property<ulong>("PrescriptionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("prescription_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MedicineId" }, "fk_pi_medicine");

                    b.HasIndex(new[] { "PrescriptionId" }, "fk_pi_prescription");

                    b.ToTable("prescription_items");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<decimal>("BatteryPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("battery_percent")
                        .HasDefaultValueSql("'100.00'");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ErrorCountSession")
                        .HasColumnType("int")
                        .HasColumnName("error_count_session");

                    b.Property<DateTime?>("EtaDeliveryAt")
                        .HasColumnType("datetime")
                        .HasColumnName("eta_delivery_at");

                    b.Property<DateTime?>("EtaReturnAt")
                        .HasColumnType("datetime")
                        .HasColumnName("eta_return_at");

                    b.Property<bool>("IsMicOn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mic_on");

                    b.Property<DateTime?>("LastHeartbeatAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitude");

                    b.Property<ulong?>("MapId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("map_id");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("ProgressLegPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_leg_pct");

                    b.Property<decimal>("ProgressOverallPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("progress_overall_pct");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('transporting','awaiting_handover','returning_to_station','at_station','completed','charging','needs_attention','manual_control','offline')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'completed'");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime?>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.HasIndex(new[] { "MapId" }, "fk_robot_map");

                    b.HasIndex(new[] { "EtaDeliveryAt" }, "idx_robot_eta_delivery");

                    b.HasIndex(new[] { "EtaReturnAt" }, "idx_robot_eta_return");

                    b.HasIndex(new[] { "Status" }, "idx_robot_status");

                    b.ToTable("robots");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.RobotCompartment", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("CategoryId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("category_id");

                    b.Property<string>("CompartmentCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("compartment_code");

                    b.Property<string>("ContentLabel")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("content_label");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<ulong?>("PatientId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("patient_id");

                    b.Property<ulong>("RobotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('locked','unlocked')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'locked'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "fk_compartment_category");

                    b.HasIndex(new[] { "PatientId" }, "fk_compartment_patient");

                    b.HasIndex(new[] { "RobotId" }, "idx_comp_robot");

                    b.HasIndex(new[] { "RobotId", "CompartmentCode" }, "uk_robot_compartment")
                        .IsUnique();

                    b.ToTable("robot_compartments");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.RobotMaintenanceLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<DateTime?>("MaintenanceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("maintenance_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong>("RobotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RobotId" }, "fk_rm_robot2");

                    b.ToTable("robot_maintenance_logs");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Room", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<ulong?>("MapId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("map_id");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("room_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MapId" }, "idx_map_id");

                    b.ToTable("rooms");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Session", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("session_token")
                        .IsFixedLength();

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_agent");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "idx_sessions_user");

                    b.HasIndex(new[] { "SessionToken" }, "session_token")
                        .IsUnique();

                    b.ToTable("sessions");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("AssignedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<ulong?>("MapId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("map_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Normal','Urgent','Critical')")
                        .HasColumnName("priority")
                        .HasDefaultValueSql("'Normal'");

                    b.Property<ulong>("RobotId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("robot_id");

                    b.Property<DateTime?>("ScheduledStartAt")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_start_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','in_progress','awaiting_handover','returning','at_station','completed','canceled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<int?>("TotalDurationS")
                        .HasColumnType("int")
                        .HasColumnName("total_duration_s");

                    b.Property<int>("TotalErrors")
                        .HasColumnType("int")
                        .HasColumnName("total_errors");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MapId" }, "fk_task_map");

                    b.HasIndex(new[] { "AssignedBy" }, "fk_tasks_assigned_by");

                    b.HasIndex(new[] { "RobotId" }, "idx_task_robot");

                    b.HasIndex(new[] { "Status" }, "idx_task_status");

                    b.ToTable("tasks");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskPatientAssignment", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("PatientId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("patient_id");

                    b.Property<ulong>("TaskId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("task_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PatientId" }, "fk_tpa_patient");

                    b.HasIndex(new[] { "TaskId" }, "fk_tpa_task");

                    b.ToTable("task_patient_assignments");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskStop", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("arrived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("custom_name");

                    b.Property<ulong?>("DestinationId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("destination_id");

                    b.Property<DateTime?>("EtaAt")
                        .HasColumnType("datetime")
                        .HasColumnName("eta_at");

                    b.Property<DateTime?>("HandedOverAt")
                        .HasColumnType("datetime")
                        .HasColumnName("handed_over_at");

                    b.Property<ulong?>("PatientId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("patient_id");

                    b.Property<int>("SeqNo")
                        .HasColumnType("int")
                        .HasColumnName("seq_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','in_progress','awaiting_handover','delivered','skipped','failed')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<ulong>("TaskId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("task_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("PatientId");

                    b.HasIndex(new[] { "DestinationId" }, "fk_stop_destination");

                    b.HasIndex(new[] { "EtaAt" }, "idx_stop_eta");

                    b.HasIndex(new[] { "Status" }, "idx_stop_status");

                    b.HasIndex(new[] { "TaskId", "SeqNo" }, "uk_task_seq")
                        .IsUnique();

                    b.ToTable("task_stops");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('admin','doctor','pharmacist')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'admin'");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("users");

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Alert", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.PrescriptionItem", "PrescriptionItem")
                        .WithMany("Alerts")
                        .HasForeignKey("PrescriptionItemId");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", "Robot")
                        .WithMany("Alerts")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alert_robot");

                    b.Navigation("PrescriptionItem");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.CompartmentAssignment", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.RobotCompartment", "Compartment")
                        .WithMany("CompartmentAssignments")
                        .HasForeignKey("CompartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ca_comp");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskStop", "Stop")
                        .WithMany("CompartmentAssignments")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ca_stop");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", "Task")
                        .WithMany("CompartmentAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ca_task");

                    b.Navigation("Compartment");

                    b.Navigation("Stop");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Log", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", "Robot")
                        .WithMany("Logs")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_robot");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskStop", "Stop")
                        .WithMany("Logs")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_log_stop");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", "Task")
                        .WithMany("Logs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_log_task");

                    b.Navigation("Robot");

                    b.Navigation("Stop");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Medicine", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.DrugCategory", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_medicine_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Room", "Room")
                        .WithMany("Patients")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_patients_rooms");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.PerformanceHistory", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", "Robot")
                        .WithMany("PerformanceHistories")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_perf_robot");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Prescription", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_presc_patient");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.User", "Users")
                        .WithMany("Prescriptions")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_presc_users");

                    b.Navigation("Patient");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Medicine", "Medicine")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pi_medicine");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pi_prescription");

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Map", "Map")
                        .WithMany("Robots")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_robot_map");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.RobotCompartment", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.CompartmentCategory", "Category")
                        .WithMany("RobotCompartments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_compartment_category");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", "Patient")
                        .WithMany("RobotCompartments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_compartment_patient");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", "Robot")
                        .WithMany("RobotCompartments")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comp_robot");

                    b.Navigation("Category");

                    b.Navigation("Patient");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.RobotMaintenanceLog", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", "Robot")
                        .WithMany("RobotMaintenanceLogs")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rm_robot2");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Room", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Map", "Map")
                        .WithMany("Rooms")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rooms_maps");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Session", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.User", "AssignedByNavigation")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tasks_assigned_by");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Map", "Map")
                        .WithMany("Tasks")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_map");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", "Robot")
                        .WithMany("Tasks")
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_robot");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Map");

                    b.Navigation("Robot");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskPatientAssignment", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", "Patient")
                        .WithMany("TaskPatientAssignments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tpa_patient");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", "Task")
                        .WithMany("TaskPatientAssignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tpa_task");

                    b.Navigation("Patient");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskStop", b =>
                {
                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Destination", "Destination")
                        .WithMany("TaskStops")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stop_destination");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", "Patient")
                        .WithMany("TaskStops")
                        .HasForeignKey("PatientId");

                    b.HasOne("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", "Task")
                        .WithMany("TaskStops")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stop_task");

                    b.Navigation("Destination");

                    b.Navigation("Patient");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.CompartmentCategory", b =>
                {
                    b.Navigation("RobotCompartments");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Destination", b =>
                {
                    b.Navigation("TaskStops");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.DrugCategory", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Map", b =>
                {
                    b.Navigation("Robots");

                    b.Navigation("Rooms");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Medicine", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Patient", b =>
                {
                    b.Navigation("Prescriptions");

                    b.Navigation("RobotCompartments");

                    b.Navigation("TaskPatientAssignments");

                    b.Navigation("TaskStops");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Prescription", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.PrescriptionItem", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Robot", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Logs");

                    b.Navigation("PerformanceHistories");

                    b.Navigation("RobotCompartments");

                    b.Navigation("RobotMaintenanceLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.RobotCompartment", b =>
                {
                    b.Navigation("CompartmentAssignments");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Room", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.Task", b =>
                {
                    b.Navigation("CompartmentAssignments");

                    b.Navigation("Logs");

                    b.Navigation("TaskPatientAssignments");

                    b.Navigation("TaskStops");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.TaskStop", b =>
                {
                    b.Navigation("CompartmentAssignments");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("API_Powered_Hospital_Delivery_Robot.Models.Entities.User", b =>
                {
                    b.Navigation("Prescriptions");

                    b.Navigation("Sessions");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
