name: 🚀 Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: 🧭 Checkout code
      uses: actions/checkout@v4

    - name: 🚀 Pull latest code from GitHub
      run: |
        cd /home/runner-user/IOT-Powered-Hospital-Delivery-Robot-with-AI
        git fetch --all
        git reset --hard origin/main

    - name: 🐳 Rebuild and restart Docker Compose
      run: |
        cd /home/runner-user/IOT-Powered-Hospital-Delivery-Robot-with-AI
        docker compose pull
        docker compose build
        docker compose up -d
