name: 🚀 Deploy to VPS

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: 🧭 Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_TOKEN }} # 🔑 Dùng token riêng để có quyền pull repo

    - name: 🚀 Build and deploy with Docker Compose
      run: |
        cd /home/runner/app/IOT-Powered-Hospital-Delivery-Robot-with-AI
        git fetch --all
        git reset --hard origin/main
        docker compose down
        docker compose build --no-cache
        docker compose up -d
